version: '3'
services:
  jekyll:
    build: .
    image: my-jekyll-site
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling --incremental
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
